### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Userpete** [jeffharrell/minicart#160]
Is there any way to make this responsive to fit the iPhone, iPad etc
Because the styles are part of the JavaScript file I cant see how you can add a media query ?

**Comment by jasonb4u** [comment]
Hello.  I see the last post here was 3 years ago.

I have a video that you need to see for errors that have not been corrected

https://www.youtube.com/watch?v=wbgWvRtzspo
[https://www.youtube.com/watch?v=wbgWvRtzspo](url)
