### ISSUE TITLE
How can I send weight to PayPal through the minicart so it can be used to calculate shipping?

### ISSUE THREAD

**Issue by SundanceClay** [jeffharrell/minicart#197]
Weight is set okay(see bottom image, weight set at 1.25), but when the cart sends to paypal it isn't there(see image just below, no weight in the cart), and I just get shipping calculations of 0. So how do I get the weight to be passed through to PayPal? Her is the link where all of this is happening:
http://sundanceclayworks.com/shop/jewelryorg/jewelryorg?2

![screen shot 2013-12-03 at 9 41 51 pm](https://f.cloud.github.com/assets/5625457/1670156/ec009432-5c8d-11e3-9ecd-d30110412e30.png)
![screen shot 2013-12-03 at 9 41 13 pm](https://f.cloud.github.com/assets/5625457/1670157/ec110b6e-5c8d-11e3-9626-9e0620a7d2e3.png)

Thanks

**Comment by kavih** [comment]
Using the latest version of minicart, this is still an issue. However, here is the function I created to automatically set the correct "weight_cart" attribute needed on the form, upon pressing checkout.
**Note**: this requires setting the hidden input form element with name "weight" to each of your products.

Hopefully this helps others.

```javascript
paypal.minicart.cart.on('checkout', updateCartWeight);

function updateCartWeight()
{
    var weight = 0;
    var form = $('#PPMiniCart form');
    
    for(var i = 0, weight = 0, item, items = paypal.minicart.cart.items(); i < items.length; i++)
    {
      item = items[i].get();
      
      for(var key in item)
      {
        if (key.indexOf('weight') >= 0)
        {
            weight += (parseFloat(item[key])*parseInt(item.quantity));
        }
      }
    }
    
    weight = weight.toFixed(1);
    
    if (form.children('input[name="weight_cart"]').length > 0)
    {
        form.children('input[name="weight_cart"]').val(weight);
    }
    else
    {
        form.append('<input type="hidden" name="weight_cart" value="'+weight+'"/>');
    }
}
```
