### ISSUE TITLE
reset() on return from PayPal throws Uncaught TypeError

### ISSUE THREAD

**Issue by krheinwald** [jeffharrell/minicart#202]
HTML file given in cancel_return parameter of PayPal form.

HTML contains

```
<script src="//cdnjs.cloudflare.com/ajax/libs/minicart/3.0.3/minicart.min.js"></script>
<script>
            paypal.minicart.reset();
</script>
```

When this page is opened on return from PayPal, an exception is thrown and the cart is not cleared:

Uncaught TypeError: Cannot call method 'destroy' of undefined

**Comment by Oxdirect** [comment]
I've been having exactly the same issue.  Placing the render statement on the return page fixed it.  Is there any chance of putting this fix on the homepage - I've spent hours getting this sorted.
