### ISSUE TITLE
Combining an API example with a string

### ISSUE THREAD

**Issue by ghost** [jeffharrell/minicart#208]
In version 2 I successfully used the script below to combine events with strings

PAYPAL.apps.MiniCart.render({
    events: {
        onCheckout: function () {
            var hasAgreed = !!document.getElementById('terms').checked;

```
        if (hasAgreed) {
            // Let the checkout continue
            return true;
        } else {
            // Stop checkout
            alert('Please agree to the Terms & Conditions');
            return false;
        }
    }
},
strings: { 
    button: "Checkout",    
    subtotal: "Total ",
    shipping: "Free UK Deliveries"   
}
```

}); 

I'm now using version 3 and have attempted to combine the two together again with no success. The two scripts which both work individually are below, I would be grateful if  someone could tie the two together in the right way in order for them to both work as one.
Thanks

paypal.minicart.render();

paypal.minicart.cart.on('checkout', function (evt) {
var hasAgreed = !!document.getElementById('terms').checked;

if (!hasAgreed) {
alert('You must agree to the terms!');
evt.preventDefault();
}
});

paypal.minicart.render({
strings: {  
subtotal:'Total ',
empty:'Your Shopping Basket Is Empty'
}
});

**Comment by lavaink** [comment]
Hi Sir,
evt.preventDefault();

I have the same problem. V2 works fine for Chrome, firefox, IE etc. at http://lavaink.com/Eco-Solvent-Inks/RolandInks/Roland-Ink-Cartridges-Eco-Sol-Max.html

But V3 only works for Firefox not Chrome sample at http://lavaink.com/Shop/Cap-Top
