### ISSUE TITLE
Shipping Calculations by Weight

### ISSUE THREAD

**Issue by salberty** [jeffharrell/minicart#235]
I'm really struggling with shipping calculations.

I had my site up and running with paypal payments standard, and all of my shipping calculations were set up to calculate by weight.  This approach is up and running and working fine.

When I try to integrate minicart, I can't get the weight to send to paypal, and it always gives a shipping cost of $0.00.

Then I tried to enter specific shipping costs in the buttons, and disabled the shipping calculations all together, and I can't even get that to pass-through to paypal.  Does anyone have a good example of a working site that passes shipping costs, ideally calculated shipping costs?

**Comment by fabriziotappero** [comment]
Here is an implementation of PayPal Minicart were shipping costs are based on item weight. Everything happens in your browser and there is no need of PayPal business account for shipping fee calculation. 
Any feedback is welcome.

http://htmlpreview.github.io/?https://github.com/fabriziotappero/minicart-plus/blob/master/minicart.html

**Comment by adpinc** [comment]
This appears to still be an issue.  I've tried a number of things and cannot get PayPal to compute weights of individual items and then compute the shipping.   Any solution would be appreciated.
