### ISSUE TITLE
minicartjs doesn't work with my dinamic site web

### ISSUE THREAD

**Issue by infomaniaco** [jeffharrell/minicart#237]
Hi to Everybody...
I have a gallery of product that I print in the index by a call of ajax Json from a php file. For every product's image there is a form personalized for the info and the prize. The problem is that minicart js recognize only forms of add to cart of the index and not the form that are obtained by a json call.
Where is the mistake?
I think minicart don't recognize paypal's form that are loaded after in asynchronous
this is the site : http://gioplast.altervista.org/#

thank you very much

**Comment by unwork** [comment]
I'm running into this issue as well. Minicart works fine from the root HTML but it won't work when triggered from an ajax-loaded HTML. Does anyone have any ideas how to make it work from an ajax page?
