### ISSUE TITLE
Binding new DOM items?

### ISSUE THREAD

**Issue by louzoid** [jeffharrell/minicart#8]
Hi Jeff,
First up thanks for building this excellent little tool - its perfect for the site i'm building!

One thing that's not really an issue as such - I have a bit of Ajax paging going on (with simple jQuery $.get) with my products so new pages of products loaded into the DOM are not being bound into the Mini cart. 

I'm going to take a look at the minicart.js when I get a mo but was wondering if you have already thought about this/have any tips for me....?

Cheers!

**Comment by unwork** [comment]
Could someone please enlighten me on how to use JavaScript's `bind();` method in order to make Minicart.js work from an AJAX-loaded page?

I've tried several different ways but my JavaScript knowledge is limited and I just can't get it to work.

Thanks in advance
Mariano

**Comment by unwork** [comment]
I was able to make it work with a little extra help from a colleague. For anyone running into a similar issue, here's the basic code in my AJAX-loaded page which allows me to trigger Mincart.js properly:

```
<div class="product-button">
	<form id='form' action="https://www.paypal.com/cgi-bin/webscr" method="post">
		<input type="hidden" name="cmd" value="_cart">
		<input type="hidden" name="add" value="1">
		<input type="hidden" name="business" value="example@minicartjs.com">
		<input type="hidden" name="item_name" value="Test Product One">
		<input type="hidden" name="item_number" value="0123456789">
		<input type="hidden" name="quantity" value="1">
		<input type="hidden" name="amount" value="100.00">
		<input type="hidden" name="currency_code" value="USD">
		<input type="hidden" name="weight_g" value="240">
		<input type="submit" name="submit" id='button' type="submit" value="USD 100.00">
	</form>
	<script>
		$( "#button" ).click(function() {
			paypal.minicart.view.bind(form);
		});			
	</script>		
</div>
```
